---

- name: Install docker-ce
  homebrew:
    name: 
     - docker
     - docker-machine
     - docker-compose
     - docker-machine-driver-xhyve
    state: latest

- name: Update docker install script
  file:
    src: setup-docker.j2 
    dest: "{{ home_dir }}/bin/setup-docker"
    mode: 0755
    state: absent
  tags:
    - docker
